abstract: Declarative HTTP::Engine
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: HTTPEx-Declare
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  HTTP::Engine: 0.0.8
  Sub::Exporter: 0
version: 0.01
